### ISSUE TITLE
SysExReceive output reverse

### ISSUE THREAD

**Issue by OscarDory** [YuuichiAkagawa/Arduino-UHS2MIDI#10]
When I try to read SysEx Messenger from Roland, instead of starting messenger F0 and ending F7, but it reverse
Is it right ?

**Comment by YuuichiAkagawa** [comment]
I don't have a roland device so I can't try it.
The following sample exchanges device inquired messages.
```
#include <UHS2-MIDI.h>

byte sysex_ir[] = { 0xF0, 0x7E, 0x7F, 0x06, 0x01, 0xF7 };

USB Usb;
UHS2MIDI_CREATE_DEFAULT_INSTANCE(&Usb);

unsigned long t0 = millis();

// -----------------------------------------------------------------------------
//
// -----------------------------------------------------------------------------
void setup()
{
  Serial.begin(115200);
  while (!Serial);

  // Listen for MIDI messages on channel 1
  MIDI.begin(1);

  MIDI.setHandleSystemExclusive(OnMidiSysEx);

  if (Usb.Init() == -1) {
    while (1); //halt
  }//if (Usb.Init() == -1...
  delay( 200 );
}

// -----------------------------------------------------------------------------
//
// -----------------------------------------------------------------------------
void loop()
{
  Usb.Task();
  // Listen to incoming notes
  MIDI.read();

  // send a note every second
  if ((millis() - t0) > 1000)
  {
    t0 = millis();
    //   Serial.print(F(".");

    MIDI.sendSysEx(sizeof(sysex_ir), sysex_ir, true);
  }
}

// -----------------------------------------------------------------------------
//
// -----------------------------------------------------------------------------
void OnMidiSysEx(byte* data, unsigned length) {
  Serial.print(F("SYSEX: ("));
  Serial.print(length);
  Serial.print(F(" bytes) "));
  for (uint16_t i = 0; i < length; i++)
  {
    Serial.print(data[i], HEX);
    Serial.print(" ");
  }
  Serial.println();
}
```

No problem to see the results.
- KORG nanoKEY2
```
SYSEX: (15 bytes) F0 7E 0 6 2 42 11 1 1 0 3 0 1 0 F7 
```
- ZOOM G1on
```
SYSEX: (15 bytes) F0 7E 0 6 2 52 63 0 0 0 31 2E 32 31 F7 
```
- PreSonus ATOM SQ
```
SYSEX: (17 bytes) F0 7E 7F 6 2 0 1 6 22 0 0 0 0 1 17 0 F7 
```

My Setting:
- Arduino UNO
- Arduino IDE 1.8.19
- MIDI library 5.0.2
- USB Host Shield Library 2.0 1.6.2

Please provide more information.

**Comment by OscarDory** [comment]
Could you explain this byte sysex_ir[] = { 0xF0, 0x7E, 0x00, 0x06, 0x01, 0xF7 };
When I turn on device Roland and serial show : F0 41 10 0 0 0 31 12 E 0 0 1 71 F7 
I also test your code above, it's correct position F7 F0, the SysEx messenger when I pressed button show F7 B0 0 1 B0 20 0 C0 0 F0

**Comment by YuuichiAkagawa** [comment]
First, there is one correction. The third message should be 0x7F.
```
byte sysex_ir[] = { 0xF0, 0x7E, 0x7F, 0x06, 0x01, 0xF7 };

```
This is an identity request in a Universal System Exclusive Message.
https://www.midi.org/specifications-old/item/table-4-universal-system-exclusive-messages

-  What is your MIDI device?
-  What is your micro controller board?
-  Can you show me your code?

**Comment by OscarDory** [comment]
What is your MIDI device? -> Roland V-1SDI
What is your micro controller board? -> Pro mini 3.3v + USB Host shield 2.0
Can you show me your code? -> I really want to show you, but I haven't found a specific solution yet. 

If you are interested, I really appreciate you helping me complete the project. Please contact me by email : jos.truonguyquyen@gmail.com.
Thanks

**Comment by YuuichiAkagawa** [comment]
> Roland V-1SDI

I found the reference manual on Roland's website.
Isn't it a control change or program change that sends a message when you press a button?
Are you sure a SysEx will be sent?

**Comment by OscarDory** [comment]
Isn't it a control change or program change that sends a message when you press a button?
Are you sure a SysEx will be sent?

Yes, Sure. In page 11. I checked with the device. It show up : 
A1: F7 B0 0 0 B0 20 0 C0 0 F0 
CC=0   V=0
CC=32 V=0
PC=0

A2: F7 B0 0 0 B0 20 0 C0 1 F0  
CC=0   V=0
CC=32 V=0
PC=1

B1 : F7 B0 0 1 B0 20 0 C0 0 F0 
CC=0   V=1
CC=32 V=0
PC=1

B1 : F7 B0 0 1 B0 20 0 C0 0 F0 
CC=0   V=1
CC=32 V=0
PC=2

A1 -> A4 or B1 -> B4 : PC = 0 -> 3
Only CC0 different value, with A value = 0, B value = 1
By the way, my project is like this one : https://github.com/DaveTheK/RolandV-1HD-Arduino-TallyLights/wiki
He use Roland V-1HD. I just want to convert the signal received from the device into a light control signal with IO pins

**Comment by YuuichiAkagawa** [comment]
F0/F7 is not needed in CC or PC.  
There is three MIDI messages.
```
A1:
B0 0 0 
B0 20 0 
C0 0
```

**Comment by OscarDory** [comment]
Is it MSB and LSB ?

**Comment by OscarDory** [comment]
Base on MSB, LSB. 
MSB : 0 x 128 + PC 
LSB : 1 x 128 + PC
A1 = 0 x 128 + 0 = 0
A2 = 0 x 128 + 1 = 1
A3 = 0 x 128 + 2 = 2
A4 = 0 x 128 + 3 = 3

B1 = 1 x 128 + 0 = 128
B2 = 1 x 128 + 1 = 129
B3 = 1 x 128 + 2 = 130
B4 = 1 x 128 + 3 = 131

Is it correct ?

**Comment by YuuichiAkagawa** [comment]
You should learn about MIDI first. I do not support the MIDI standard and specific device.
