### ISSUE TITLE
Question: use of STM32F4 possible?

### ISSUE THREAD

**Issue by SunboX** [YuuichiAkagawa/Arduino-UHS2MIDI#12]
Hi,

Can this also work with an STM32F4 (blackpill)? If so, can you point me in the right direction?

Greetings and thanks,
André

**Comment by YuuichiAkagawa** [comment]
I don't know.
This library assumes that the USB Host Shield is working.
I can only say that it works if you have a USB Host Shiled available.

**Comment by YuuichiAkagawa** [comment]
Closing this issue due to lack of feedback. Feel free to reopen the issue again if needed.
