### ISSUE TITLE
Support for new ESP32 USB Soft Host Library ?

### ISSUE THREAD

**Issue by quangvankts** [YuuichiAkagawa/Arduino-UHS2MIDI#2]
Hi YuuichiAkagawa

Thank you for your time working on this project
It works really well for my ESP32 - USB Host Shield Mini 2.0 setup

However there is new library from sdima1357, make it possible to connect ESP32 directly to USB devices without the USB Host Shield:
https://github.com/sdima1357/esp32_usb_soft_host
And an Arduino version here:
https://github.com/tobozo/ESP32-USB-Soft-Host

So is it possible to make your Arduino-UHS2MIDI library work in combination with this new ESP32-USB-Soft-Host library ? If you can it would be much appreciated !

Thank you

**Comment by YuuichiAkagawa** [comment]
> So is it possible to make your Arduino-UHS2MIDI library work in combination with this new ESP32-USB-Soft-Host library ?

No. This library only works with the USB Host Shield Library 2.0.
You will need to develop your own MIDI class driver and MIDI transport layer.

**Comment by quangvankts** [comment]
Ah ok thank you !
