### ISSUE TITLE
uhs2MidiTransport RecvData() handle only one event packet from midi device transfer

### ISSUE THREAD

**Issue by Silray** [YuuichiAkagawa/Arduino-UHS2MIDI#4]
Hi Yuuichi,
I use you great library to develop a small midi-engine, which allow me to receive midi data from some midi-keyoards and play them without PC.
I get the midi-data from midi-keyboards via usb and/or via serial. 
My setup is ESP32, USB Host Shield and VS1053b (plus some buttons, encoder and display;-)).
It works fine so far, with one keyboard and slow key pressing. But I lost lot of midi data if I use 2 keyboards or try to press several keys in parallel.

I analysed this problem last days and found the possible reason.
In this way I would like to describe the problem and my solution.

The Problem.
I read up to 4 midi devices in a read-sequence using read() from your uhs2MidiTransport-class. 
launchCallback() from MidiInterface get no more than one midi command.
In the next sequence read() read "new" data from the same midi device, the another commands in buffer are lost.
My sequence repeated after 1 ms. My first idea was to be faster (at first 0.1ms, then with full speed of loop()), without change in behaviour.

The solution.
In short - I change the kind of data reading from midi device.
uhs2MidiTransport::RecvData() read now all data (64 Bytes) from USBH_MIDI::RecvData() and copy only valid commands without packet header to buffer which will be read (and parsed) later to the end within a sequence.
And it works, all data is taken over.
Now my adaptation suggestion:

new array in uhs2MidiTransport
`    
uint8_t mBuf[MIDI_EVENT_PACKET_SIZE];
`
changes inside uhs2MidiTransport::RecvData()

uint8_t RecvData(uint8_t *buf)
{
  uint16_t rcvd;
  uint8_t rc = USBH_MIDI::RecvData( &rcvd, mBuf);
  if( rc != 0 )
  {
    buf[0] = 0;
    return 0;
  }
  else
  {
    rc = 0;
    rcvd = 0;
    usbMidiEventPacket_t *p = (usbMidiEventPacket_t *)mBuf;
    for(int i = 0; i < MIDI_EVENT_PACKET_SIZE >> 2; i++)
    {
      if(p->p.header > 0
      {
        // Serial.printf("Evt:%02X %02X %02X %02X\n", p->p.header, p->p.byte1, p->p.byte2, p->p.byte3);
        buf[rcvd++] = p->p.byte1;
        buf[rcvd++] = p->p.byte2;
        buf[rcvd++] = p->p.byte3;
        rc += 3;
      }
      p++;
    }
  }
  return rc;
}

Changes inside uhs2MidiTransport::available()
`    unsigned available()
    {
      // consume mRxBuffer first, before getting a new packet
      if (mRxLength > 0)
        return mRxLength;

      mRxIndex = 0;
      auto len = (size_t)RecvData(mRxBuf);
      if (mRxBuf[0] != 0) 
        mRxLength = len;
      return mRxLength;
    };
`
Incidentally, with the test and skipping the other cable number, this data is irrevocably lost.

The fourth change is the type of data query somewhere in the Application.
So I ask for the data
` 
     // My objects declarations:
      // _transport = new uhs2MidiTransport(_usb, _cn);
      // _midi = new midi::MidiInterface<uhs2MidiTransport>(*_transport);
    void read() 
    {
      do
      {
        _midi->read();
      } while (_transport->available()>0);
    }

`
 I apologize for my bad englisch.

**Comment by YuuichiAkagawa** [comment]
I tried two MIDI keyboards without modifying the library. 
It seems to work.
- ESP32 DevKitC
- UHS mini r1.1
- USB hub (Powered)
- AKAI MPK mini MK3
- KORG nanoKEY
```
#include <UHS2-MIDI.h>
#include <usbhub.h>
USB Usb;
USBHub  Hub1(&Usb);

UHS2MIDI_CREATE_INSTANCE(&Usb, 0, MIDI1);
UHS2MIDI_CREATE_INSTANCE(&Usb, 0, MIDI2);

void handleNoteOn1(byte inChannel, byte inNumber, byte inVelocity)
{
  Serial.print("NoteOn(1)  ");
  Serial.print(inNumber);
  Serial.print("\tvelocity: ");
  Serial.println(inVelocity);
}

void handleNoteOff1(byte inChannel, byte inNumber, byte inVelocity)
{
  Serial.print("NoteOff(1) ");
  Serial.print(inNumber);
  Serial.print("\tvelocity: ");
  Serial.println(inVelocity);
}

void handleNoteOn2(byte inChannel, byte inNumber, byte inVelocity)
{
  Serial.print("NoteOn(2)  ");
  Serial.print(inNumber);
  Serial.print("\tvelocity: ");
  Serial.println(inVelocity);
}

void handleNoteOff2(byte inChannel, byte inNumber, byte inVelocity)
{
  Serial.print("NoteOff(2) ");
  Serial.print(inNumber);
  Serial.print("\tvelocity: ");
  Serial.println(inVelocity);
}

void setup() {
  Serial.begin(115200);
  
  MIDI1.begin(1);
  MIDI2.begin(1); 
  MIDI1.setHandleNoteOn(handleNoteOn1);
  MIDI1.setHandleNoteOff(handleNoteOff1);
  MIDI2.setHandleNoteOn(handleNoteOn2);
  MIDI2.setHandleNoteOff(handleNoteOff2);

  if (Usb.Init() == -1) {
    while (1); //halt
  }//if (Usb.Init() == -1...
  delay( 200 );

}

void loop() {
  Usb.Task();
  MIDI1.read();
  MIDI2.read();
}
```

**Comment by Silray** [comment]
Hi Yuuichi,
thank you for the answer.
Your explanation with example is very plausible, but does not address the problem I've described.
Each of the callbacks takes about 13 ms and is a bottleneck in your example.
An Instrument is only evalueted every 25 ms.
A MIDI-buffer can only store 16 MIDI-commands, which can quickly lead to loss of data by chord or arpeggio.

I found a link, with deep explanation.
https://gearspace.com/board/electronic-music-instruments-and-electronic-music-production/1112683-do-usb-midi-interfaces-send-midi-faster-than-midi-spec.html
Entries #31 and #54 are very important.

I'm of the opinion that a MIDI-buffer always has to be emptied while read().

**Comment by YuuichiAkagawa** [comment]
I understood your point.  Please wait.

**Comment by YuuichiAkagawa** [comment]
USBH_MIDI::RecvData(uint8_t *outBuf) is already implemented in bulk read.

The key to your speedup is this code.
```
void read()
{
  do
  {
    _midi->read();
  } while (_transport->available() > 0);
}
```

I tried Three MIDI keyboards without modifying the library.
- ESP32 DevKitC
- UHS mini r1.1
- USB hub (Powered)
- KORG SQ-1
- KORG microKEY Air 25
- AKAI MPK mini MK3

And I measured the callback time using a logic analyzer.
If there is a continuous message, the callback is invoked at intervals of about 3.5 microseconds.

![UHS2MIDI_TEST](https://user-images.githubusercontent.com/926923/125154376-b1d70400-e194-11eb-9cd9-ac30d4b5f808.png)

### SQ-1
Channel A adn channel B run in parallel. MIDI Clock enabled.
![UHS2MIDI_TEST-SQ1](https://user-images.githubusercontent.com/926923/125154400-cf0bd280-e194-11eb-87c1-435519c24b68.png)

### microKEY
Arpeggiator: trigger, 4 notes
![UHS2MIDI_TEST-microKEY](https://user-images.githubusercontent.com/926923/125154403-d29f5980-e194-11eb-9704-1fc8285f4c14.png)

### MPKmini
Arpeggiator: Random, 3 notes
Detailed data is omitted because it is a single note on/off.

### Code
```
#include <UHS2-MIDI.h>
#include <usbhub.h>
USB Usb;
USBHub  Hub1(&Usb);

#define ENABLE_MIDI2
#define ENABLE_MIDI3

#define DEBUG_PIN1 14
#define DEBUG_PIN2 12
#define DEBUG_PIN3 27
#define DEBUG_PIN4 26
#define DEBUG_PIN5 25
#define DEBUG_PIN6 33
#define DEBUG_PIN7 32


UHS2MIDI_CREATE_INSTANCE(&Usb, 0, MIDI1);

#ifdef ENABLE_MIDI2
UHS2MIDI_CREATE_INSTANCE(&Usb, 0, MIDI2);
#endif

#ifdef ENABLE_MIDI3
UHS2MIDI_CREATE_INSTANCE(&Usb, 0, MIDI3);
#endif

void handleNoteOn1(byte inChannel, byte inNumber, byte inVelocity)
{
  digitalWrite(DEBUG_PIN1, !digitalRead(DEBUG_PIN1));
}

void handleNoteOff1(byte inChannel, byte inNumber, byte inVelocity)
{
  digitalWrite(DEBUG_PIN2, !digitalRead(DEBUG_PIN2));
}

void handleClock1()
{
  digitalWrite(DEBUG_PIN3, !digitalRead(DEBUG_PIN3));
}

#ifdef ENABLE_MIDI2
void handleNoteOn2(byte inChannel, byte inNumber, byte inVelocity)
{
  digitalWrite(DEBUG_PIN4, !digitalRead(DEBUG_PIN4));
}

void handleNoteOff2(byte inChannel, byte inNumber, byte inVelocity)
{
  digitalWrite(DEBUG_PIN5, !digitalRead(DEBUG_PIN5));
}
#endif

#ifdef ENABLE_MIDI3
void handleNoteOn3(byte inChannel, byte inNumber, byte inVelocity)
{
  digitalWrite(DEBUG_PIN6, !digitalRead(DEBUG_PIN6));
}

void handleNoteOff3(byte inChannel, byte inNumber, byte inVelocity)
{
  digitalWrite(DEBUG_PIN7, !digitalRead(DEBUG_PIN7));
}
#endif

void setup() {
  pinMode(DEBUG_PIN1, OUTPUT); digitalWrite(DEBUG_PIN1, LOW);
  pinMode(DEBUG_PIN2, OUTPUT); digitalWrite(DEBUG_PIN2, LOW);
  pinMode(DEBUG_PIN3, OUTPUT); digitalWrite(DEBUG_PIN3, LOW);

#ifdef ENABLE_MIDI2
  pinMode(DEBUG_PIN4, OUTPUT); digitalWrite(DEBUG_PIN4, LOW);
  pinMode(DEBUG_PIN5, OUTPUT); digitalWrite(DEBUG_PIN5, LOW);
#endif

#ifdef ENABLE_MIDI3
  pinMode(DEBUG_PIN6, OUTPUT); digitalWrite(DEBUG_PIN6, LOW);
  pinMode(DEBUG_PIN7, OUTPUT); digitalWrite(DEBUG_PIN7, LOW);
#endif
  
  MIDI1.begin(MIDI_CHANNEL_OMNI);

#ifdef ENABLE_MIDI2
  MIDI2.begin(MIDI_CHANNEL_OMNI); 
#endif

#ifdef ENABLE_MIDI3
  MIDI3.begin(MIDI_CHANNEL_OMNI); 
#endif

  MIDI1.setHandleNoteOn(handleNoteOn1);
  MIDI1.setHandleNoteOff(handleNoteOff1);
  MIDI1.setHandleClock(handleClock1);

#ifdef ENABLE_MIDI2
  MIDI2.setHandleNoteOn(handleNoteOn2);
  MIDI2.setHandleNoteOff(handleNoteOff2);
#endif

#ifdef ENABLE_MIDI3
  MIDI3.setHandleNoteOn(handleNoteOn3);
  MIDI3.setHandleNoteOff(handleNoteOff3);
#endif

  if (Usb.Init() == -1) {
    while (1); //halt
  }//if (Usb.Init() == -1...
  delay( 200 );

}

void loop() {
  Usb.Task();
  do {
    MIDI1.read();
  }while( __uhs2MIDI1.available() > 0);

#ifdef ENABLE_MIDI2
  do {
    MIDI2.read();
  }while( __uhs2MIDI2.available() > 0);
#endif

#ifdef ENABLE_MIDI3
  do {
    MIDI3.read();
  }while( __uhs2MIDI3.available() > 0);
#endif
}

```

**Comment by Inviz** [comment]
Hello. I love your libraries, but I have a similar question. So I made a bi-directional midi converter that controls led strip based on incoming and outgoing notes. The deal is that led stuff takes about 10ms to update, and that makes midi messages incoming from via USB be skipped sometimes. If I turn off my led stuff, things are reliable. It doesn't seem that there're too many messages, it's their timing (like multiple channel notes being played together, etc). I'm using an iPad app that plays midi songs as one of the participants, so there could be more notes per second than keyboards.

How do I approach this situation? Is there a way to buffer up messages while other stuff is happening?

**Comment by YuuichiAkagawa** [comment]
We don't have a solution.
You will need to implement buffer control and asynchronous processing on your own.

https://github.com/FortySevenEffects/arduino_midi_library/wiki/Using-Callbacks#my-sketch-is-very-slow-whats-going-on-

**Comment by Inviz** [comment]
The link you provided talks about buffer, but Midi.read only pulls up one message, right?

does calling Midi.read multiple times within a single loop tick make any difference? Would it take multiple buffered messages from the queue? 

 USB transport should not be losing any messages, correct? They are still in the queue?


Thanks a lot!

**Comment by YuuichiAkagawa** [comment]
What I meant to say is that in the Arduino MIDI library, you need to call MIDI.read() quickly.
The USB Host Library is also polling-based, so if the call is delayed, the message will be lost.

**Comment by Inviz** [comment]
Right, thanks. So internally there's no queue or buffer of anything? Neither in USBH, nor in Midi lib? And if there is, calling Midi.read() repeatedly inside a single loop iteration does nothing? Like `while (Midi.read()) { } ...`

Apologies for dumb questions, but your answers are very much appreciated.

**Comment by YuuichiAkagawa** [comment]
In USB, MIDI messages are received by the host requesting them from the device. They are not sent from the device side when you press the keyboard.

If multiple MIDI messages are sent in a single request, it receives and holds them. Then, each time Midi.read() is called, it retrieves one MIDI message.

**Comment by Inviz** [comment]
Got it, so it may make sense to call Midi.read multiple times. I appreciate you and your work on the libraries. Have a nice day

**Comment by YuuichiAkagawa** [comment]
Closing this issue due to lack of feedback. Feel free to reopen the issue again if needed.
