### ISSUE TITLE
Midi from Novation Launchkey

### ISSUE THREAD

**Issue by swordsreversed** [YuuichiAkagawa/Arduino-UHS2MIDI#5]
HI,

Not sure if this is the right place to ask but here goes...

I'm trying to use the Midi converter skecth to send midi from my Launchkey MK3 chanel 1 to my Volca Fm (also channel 1). I run the sketch and i get nothing. If i run a sketch using a different library to get midi from Ableton to the Volca, i have no problems, so obviously the launchkey is not being seen.

Do you have any ideas on what i could try next? I'm powering a Leonardo by power supply and connecting the LK by USB OTG adapter.

**Comment by YuuichiAkagawa** [comment]
Oh, Novation.

Please run USB_desc or USB_MIDI_desc to report the output.
- https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/USB_desc/USB_desc.ino
- https://github.com/YuuichiAkagawa/USBH_MIDI/blob/master/examples/USB_MIDI_desc/USB_MIDI_desc.ino

Novation devices may require special handling.

https://github.com/YuuichiAkagawa/USBH_MIDI/blob/3c035c21258a161eef6c61c21632d60802f7dc19/usbh_midi.cpp#L285-L306

**Comment by swordsreversed** [comment]
Ok i'll give it a shot. Thanks.

**Comment by YuuichiAkagawa** [comment]
Closing this issue due to lack of feedback. Feel free to reopen the issue again if needed.
