### ISSUE TITLE
Setting the full USB-Midi Speed (Baud-rate)

### ISSUE THREAD

**Issue by dennis-germany-1981** [YuuichiAkagawa/Arduino-UHS2MIDI#8]
Hi,
I hope this is the right place to post the question.

What is the default baud rate for USB-MIDI in this library?

I definitely want to send midi data (send/receive) with the fastest possible baud rate and avoid slow midi with 31250 !!

Does something have to be configured to achieve the full USB-MIDI speed or is the fastest baud rate already preset by default?

**Comment by YuuichiAkagawa** [comment]
This library depends on the behavior of the [USB Host Library](https://github.com/felis/USB_Host_Shield_2.0). If the USB MIDI controller is Full Speed, it will work at Full Speed.
There is no concept of baud rate setting.

**Comment by dennis-germany-1981** [comment]
Thanks for the quick and detailed answer.
