### ISSUE TITLE
USB is not recognized by the MEDELI AKX10 KEYBOARD

### ISSUE THREAD

**Issue by dennis-germany-1981** [YuuichiAkagawa/Arduino-UHS2MIDI#9]
Hi Yuuichi, 

I hope you can help or fix my problem.

I have a MEDELI AKX10 Keyboard.
The Keyboard provides USB MIDI and USB AUDIO over the USB Port.

But, the USB-HOST Shield isn't recognized by the Keyboard !

Is there some tweaking nescessary and possible to work with the MEDELI Keyboard 
- either in the MIDI Library or in the USB HOST Library ?

Many thanks in advance for your reply
Dennis

Here's my USB-Dump-File:

01
--

Device descriptor: 
Descriptor Length:	12
Descriptor type:	01
USB version:		0200
Device class:		00
Device Subclass:	00
Device Protocol:	00
Max.packet size:	40
Vendor  ID:		0A67
Product ID:		3620
Revision ID:		0100
Mfg.string index:	01
Prod.string index:	02
Serial number index:	06
Number of conf.:	01

Configuration descriptor:
Total length:		00F9
Num.intf:		04
Conf.value:		01
Conf.string:		00
Attr.:			C0
Max.pwr:		05

Interface descriptor:
Intf.number:		00
Alt.:			00
Endpoints:		00
Intf. Class:		01
Intf. Subclass:		01
Intf. Protocol:		00
Intf.string:		00

<<<AUDIO_CONTROL>>>
Unknown descriptor:
Length:		0B
Type:		24
Contents:	010001350003010203
Unknown descriptor:
Length:		0C
Type:		24
Contents:	02010101000203000000
Unknown descriptor:
Length:		09
Type:		24
Contents:	03020103000100
Unknown descriptor:
Length:		0C
Type:		24
Contents:	02030102000203000000
Unknown descriptor:
Length:		09
Type:		24
Contents:	03040101000300

Interface descriptor:
Intf.number:		01
Alt.:			00
Endpoints:		00
Intf. Class:		01
Intf. Subclass:		02
Intf. Protocol:		00
Intf.string:		00

<<<AUDIO_STREAMING>>>

Interface descriptor:
Intf.number:		01
Alt.:			01
Endpoints:		01
Intf. Class:		01
Intf. Subclass:		02
Intf. Protocol:		00
Intf.string:		00

<<<AUDIO_STREAMING>>>
Unknown descriptor:
Length:		07
Type:		24
Contents:	0101010100
Unknown descriptor:
Length:		0B
Type:		24
Contents:	02010202100144AC00

Endpoint descriptor:
Endpoint address:	01
Attr.:			09
Max.pkt size:		00C0
Polling interval:	04
Unknown descriptor:
Length:		07
Type:		25
Contents:	0101000000

Interface descriptor:
Intf.number:		02
Alt.:			00
Endpoints:		00
Intf. Class:		01
Intf. Subclass:		02
Intf. Protocol:		00
Intf.string:		00

<<<AUDIO_STREAMING>>>

Interface descriptor:
Intf.number:		02
Alt.:			01
Endpoints:		01
Intf. Class:		01
Intf. Subclass:		02
Intf. Protocol:		00
Intf.string:		00

<<<AUDIO_STREAMING>>>
Unknown descriptor:
Length:		07
Type:		24
Contents:	0104010100
Unknown descriptor:
Length:		0B
Type:		24
Contents:	02010202100144AC00

Endpoint descriptor:
Endpoint address:	82
Attr.:			01
Max.pkt size:		00B4
Polling interval:	04
Unknown descriptor:
Length:		07
Type:		25
Contents:	0101000000

Interface descriptor:
Intf.number:		03
Alt.:			00
Endpoints:		02
Intf. Class:		01
Intf. Subclass:		03
Intf. Protocol:		00
Intf.string:		00

<<<MIDIStreaming>>>

MS Interface descriptor
07240100014100
DescriptorSubtype: 01
CS_INTERFACE :	MS_HEADER
MIDIStreaming SubClass Specification Release number: 0100
wTotalLength:		0041

MS Interface descriptor
062402010100
DescriptorSubtype: 02
CS_INTERFACE :	MIDI_IN_JACK(Embedded)
JackType:	01
JackID:		01

MS Interface descriptor
062402020200
DescriptorSubtype: 02
CS_INTERFACE :	MIDI_IN_JACK(External)
JackType:	02
JackID:		02

MS Interface descriptor
092403010301020100
DescriptorSubtype: 03
CS_INTERFACE :	MIDI_OUT_JACK(Embedded)
JackType:	01
JackID:		03
NrInputPins:	01
020100

MS Interface descriptor
092403020401010100
DescriptorSubtype: 03
CS_INTERFACE :	MIDI_OUT_JACK(External)
JackType:	02
JackID:		04
NrInputPins:	01
010100

Endpoint descriptor:
Endpoint address:	03
Attr.:			02
Max.pkt size:		0040
Polling interval:	00

MS Endpoint descriptor
0525010101
CS_ENDPOINT :	MS_GENERAL
bNumEmbMIDIJack: 01
01

Endpoint descriptor:
Endpoint address:	84
Attr.:			02
Max.pkt size:		0040
Polling interval:	00

MS Endpoint descriptor
0525010103
CS_ENDPOINT :	MS_GENERAL
bNumEmbMIDIJack: 01
03

Addr:1(0.0.1)

**Comment by YuuichiAkagawa** [comment]
Please enable debug mode and run USBH_MIDI_dump.

Enable Debug mode
https://github.com/felis/USB_Host_Shield_2.0#enable-debugging

USBH_MIDI_dump
Examples > USB Host Shield Library 2.0 > USBH_MIDI > USBH_MIDI_dump
https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/USBH_MIDI/USBH_MIDI_dump/USBH_MIDI_dump.ino

**Comment by dennis-germany-1981** [comment]
I don't know exactly what happened, but after enabling the debug mode and executing the Midi Dump Sketch the Arduino and the USB Host Shield are now recognized by the keyboard and MIDI is both sent and received. 

Thank you and best regards 
Dennis
